ai_ml:
  enable_anomaly_detection: true
  model_endpoint: http://localhost:5000/predict
deletion_packet:
  deletion_time: 100
endpoints:
- hostname: endpoint1.local
  id: endpoint-1
  ip_address: 192.168.1.100
  os: Windows
- hostname: endpoint2.local
  id: endpoint-2
  ip_address: 192.168.1.101
  os: Linux
firewall:
  rules:
  - allowed_domains:
    - google.com
    - example.com
    allowed_ips:
    - 192.168.1.1
    application: brave
    blocked_domains:
    - shady.com
    blocked_ips:
    - 35.174.127.31
    - 142.251.42.14
    - 192.168.0.1
    - 52.168.117.175
    - 142.250.77.182
    - 51.105.71.136
    - 117.18.232.200
    - 103.57.86.142
    - 13.69.116.109
    - 10.0.0.1
    - 31.13.79.35
    id: 1
    protocols:
    - TCP
    - UDP
  - allowed_domains:
    - microsoft.com
    allowed_ips: []
    application: VSCode
    blocked_domains: []
    blocked_ips: []
    id: 2
    protocols:
    - TCP
  - allowed_domains:
    - microsoft.com
    allowed_ips: []
    application: VSCode
    blocked_domains: []
    blocked_ips: []
    id: 0
    protocols:
    - TCP
logging:
  log_file: /var/log/firewall-tool.log
  log_level: info
  max_age: 30
  max_backups: 3
  max_size: 100
mnist_param:
  mnist_creation: true
  mnist_saving_dir: ../model_pipeline_files/data/mnist/
  png_deletion: true
model:
  batch_size: 64
  cuda_code: cpu
  model_dim: 28
  model_dir_packet_data: ../model_pipeline_files/models/packet_data/model1.pth
  model_dir_packet_features: ../model_pipeline_files/models/packet_features/
  model_python_file_loc: ../model_pipeline_files/inferencer.py
  num_classes: 1
monitoring:
  alert_thresholds:
    abnormal_traffic: 1000
    blocked_attempts: 10
  enable: true
  log_file: /var/log/firewall-monitor.log
network:
  enable_deep_packet_inspection: true
  proxy_enabled: true
  self_signed_tls_cert: /path/to/self-signed-cert.pem
png_param:
  matrix_size: 784
  pcap_deletion: true
  png_saving_dir: ../model_pipeline_files/data/pngs/
  png_size: 28
  python_file_loc: ../model_pipeline_files/session2png_mnsit.py
  threads_alloc: 5
  trim: true
splitcap:
  Directory_session_wise_split_pcap: ../model_pipeline_files/packets/session_wise_packets/
  Directory_store_actual_pcap: ../model_pipeline_files/packets/captured_packets/
  Directory_store_pcap: ../model_pipeline_files/packets/
  Duration_of_collecting_pcap: 10
  Splitcap_location: ../model_pipeline_files/
  deletion_after_split: true
web_console:
  admin_users:
  - admin
  allowed_ips:
  - 192.168.1.1
  blocked_ips: []
  port: 8080
