firewall:
  rules:
  - id: 1
    application: brave
    allowed_domains:
    - google.com
    - example.com
    blocked_domains:
    - shady.com
    allowed_ips:
    - 192.168.1.1
    blocked_ips:
    - 10.0.0.1
    protocols:
    - TCP
    - UDP
  - id: 2
    application: VSCode
    allowed_domains:
    - microsoft.com
    blocked_domains: []
    allowed_ips: []
    blocked_ips: []
    protocols:
    - TCP
  - id: 0
    application: VSCode
    allowed_domains:
    - microsoft.com
    blocked_domains: []
    allowed_ips: []
    blocked_ips: []
    protocols:
    - TCP
monitoring:
  enable: true
  log_file: /var/log/firewall-monitor.log
  alert_thresholds:
    abnormal_traffic: 1000
    blocked_attempts: 10
ai_ml:
  model_endpoint: http://localhost:5000/predict
  enable_anomaly_detection: true
endpoints:
- id: endpoint-1
  os: Windows
  ip_address: 192.168.1.100
  hostname: endpoint1.local
- id: endpoint-2
  os: Linux
  ip_address: 192.168.1.101
  hostname: endpoint2.local
web_console:
  port: 8080
  allowed_ips:
  - 192.168.1.1
  blocked_ips: []
  admin_users:
  - admin
logging:
  log_level: info
  log_file: /var/log/firewall-tool.log
  max_size: 100
  max_backups: 3
  max_age: 30
network:
  enable_deep_packet_inspection: true
  self_signed_tls_cert: /path/to/self-signed-cert.pem
  proxy_enabled: true
